[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd apps && npm ci --production=false"]

[phases.build]
cmds = ["cd apps && npm run build"]

[start]
cmd = "cd apps && npm run start:prod"

[variables]
NODE_ENV = "production"